services:
  - type: web
    name: food-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
